[package]
name = "diagraph"
version = "0.2.1"
entrypoint = "lib.typ"
authors = ["Robotechnic", "Malo <@MDLC01>"]
license = "MIT"
description = "Graphviz bindings for Typst"
repository = "https://github.com/Robotechnic/diagraph.git"
keywords = ["graphviz", "graph", "diagram"]
categories = ["components", "visualization", "integration"]
compiler = "0.11.0"
exclude = ["graphviz_interface/*", "examples/*", ".gitignore", "Makefile"]
